# Generated by Django 4.2.3 on 2023-08-02 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('contract_number', models.CharField(blank=True, max_length=16, unique=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_number', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('contract_date', models.DateTimeField(null=True)),
                ('contractor', models.CharField(blank=True, max_length=20)),
                ('shipping_company', models.CharField(blank=True, max_length=40)),
                ('customer_company', models.CharField(blank=True, max_length=40)),
                ('departure_address', models.CharField(blank=True, max_length=80)),
                ('arrival_address', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'db_table': 'contract',
            },
        ),
        migrations.CreateModel(
            name='PackageLog',
            fields=[
                ('package_number', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.IntegerField(null=True)),
                ('shipping_stage', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'package_log',
                'unique_together': {('package_number', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('contract_number', models.CharField(blank=True, db_index=True, max_length=16)),
                ('package_number', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('package_name', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='CWL.contract')),
            ],
            options={
                'db_table': 'package',
            },
        ),
    ]
